apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-red.fullname" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}