{{- if .Values.keycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-{{ include "node-red.fullname" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-client-id: {{ required "node-red.keycloak.clientID is required if keycloak configuration is specified." .Values.keycloak.clientID | b64enc | quote }}
  keycloak-client-secret: {{ required "node-red.keycloak.clientSecret is required if keycloak configuration is specified." .Values.keycloak.clientSecret | b64enc | quote }}
{{- end }}