{{- if .Values.s3 }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-{{ include "node-red.fullname" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
type: Opaque
data:
  s3-access-key-id: {{ required "s3.s3AccessKeyId is required if s3 configuration is specified." .Values.s3.s3AccessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ required "s3.s3SecretAccessKey is required if s3 configuration is specified." .Values.s3.s3SecretAccessKey | b64enc | quote }}
{{- end }}
